# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  
name: '1.0.$(Rev:r)'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'Serializer/Serializer.csproj'
    arguments: '--configuration $(BuildConfiguration) /p:Version=$(Build.BuildNumber)'
