trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  
name: '1.0.$(Rev:r)'

steps:
- task: DotNetCoreCLI@2
  displayName: 'Build Library'
  inputs:
    command: 'build'
    projects: 'Serializer/Serializer.csproj'
    arguments: '--configuration $(BuildConfiguration) /p:Version=$(Build.BuildNumber)'

- task: DotNetCoreCLI@2
  displayName: 'Test Library'
  inputs:
    command: 'test'
    projects: 'SerializerTest/SerializerTest.csproj'
    testRunTitle: 'Multipart Serializer Test'

- task: DotNetCoreCLI@2
  displayName: 'Publish library'
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: 'Serializer/Serializer.csproj'
    arguments: '--configuration $(BuildConfiguration) /p:Version=$(Build.BuildNumber)'
    
- task: DotNetCoreCLI@2
  displayName: 'Pack Library'
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  inputs:
    command: 'pack'
    packagesToPack: '**/*.csproj'
    versioningScheme: 'byBuildNumber'

- task: DotNetCoreCLI@2
  displayName: 'Uploading to Tiber Health Nuget'
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '0bd21b8b-3ec1-4cf1-9e2a-c491e2a220a5'

- task: NuGetCommand@2
  displayName: 'Push to nuget.org'
  condition: and(succeeded(), eq(variables.nuget, true))
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'Nuget.Org'

- task: GitHubRelease@1
  displayName: 'Creating Release on GitHub'
  condition: and(succeeded(), eq(variables.nuget, true))
  inputs:
    gitHubConnection: 'Tiberhealth GitHub'
    repositoryName: 'tiberhealth/MultipartSerializer'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'userSpecifiedTag'
    tag: '$(Build.BuildNumber)'
    changeLogCompareToRelease: 'lastFullRelease'
    changeLogType: 'commitBased'


